stages:
  - test

cypress_headless:
  stage: test
  image: cypress/browsers:chrome87
  script:
    - npm install
    - npm run runHeadless --spec "cypress/integration/APITest.spec.js,cypress/integration/webAutomation.spec.js"
