stages:
  - test

cypress_headless:
  stage: test
  image: cypress/base:14
  script:
    - npm install
    - npm run runHeadless --spec "cypress\integration\AQA-SR\APITest.spec.js,cypress\integration\AQA-SR\webAutomation.spec.js"

cypress_headed:
  stage: test
  image: cypress/base:14
  script:
    - npm install
    - npm run runHeaded --spec "cypress\integration\AQA-SR\APITest.spec.js,cypress\integration\AQA-SR\webAutomation.spec.js"
