stages:
  - test

cypress_headless:
  stage: test
  image: cypress/browsers:latest
  script:
    - npm install
    - npm run runHeadless --spec "cypress/integration/AQA-SR/APITest.spec.js,cypress/integration/AQA-SR/webAutomation.spec.js"
    - npx cypress run